shortlist-digital/tapestry-lite

src/server/handlers/dynamic.js
src/server/routing/route-wrapper.js

Adding the catch all 404 route during  the Route Wrapping process to cut down on dynamic handler logic.
This cut down of logic is not yet apparent. But it will be!

Handling the 404 router with react-router and route-wrapper

---

src/server/render/tree-to-html.js

We should replace this with `react-loadable` once we wrap our heads around it.

Removed getComponent support

---

package.json
src/client/root.js
src/server/handlers/dynamic.js
src/server/routing/prepare-app-routes.js
src/server/utilities/match-routes.js
yarn.lock

This is copied directly from `react-router`, had to tweak the 404 catch-all route to fall through correctly.

Replace react-router matchRoutes with utility script

---

package.json
src/client/root.js
src/server/render/default-document/index.js
src/server/render/default-error/index.js
src/server/render/error-view.js
src/server/render/missing-view/index.js
src/server/routing/match-routes.js
src/server/routing/prepare-app-routes.js
yarn.lock

* Replaced `path-to-regexp` and logic with [`matchit`](https://github.com/lukeed/matchit), a smaller/faster alternative.
* Updated in browser debugging to `#development` to match AMP, thoughts?
* Removed all `prop-types`
* Removed `idx` from the single place it was used in the client bundle
* Simplified `prepare-app-routes.js` as we no longer need `exact: true`

Byte savin

---

src/config/createWebpackConfig.js

Two compilers - both clearing the console output
1. Error in the server compiler
2. Success in the client compiler
3. Client compiler clears output
4. Can't see the server error
5. Set the environment to test so you can see the error

Verbose console output all the time

---

src/server/render/tree-to-html.js
test/server/document.test.js

Allows us to manage a lot of validation procedures from AWS, Google, Facebook etc through tapestry.

Add disable doctype option

---

CHANGELOG.md
package.json
src/client/root.js
src/server/routing/default-routes.js

- Removed `matchRoutes` helper from client bundle
- Added a default object argument to `default-routes` for safety
Tests are passing
Confirmed expected behaviour in browser

Remove matchRoutes from client

---

CHANGELOG.md
package.json
readme.md
src/config/hot-server.js
src/config/hot.js

A couple of the team had mentioned the "not accepted" bug happening on all the projects.
Steps to reproduce were:
- Change a jsx file (not styles)
- In the console you'd get a hot-reload error talking about a module not accepted
- Prior to the recent ["verbosity" change](https://github.com/shortlist-digital/tapestry-lite/commit/d44703b1de2f226687bfb85ac3f6dd42d7474fee) in the webpack configs, this failure would overwrite a terminal output message from the _client_ webpack, saying that the module _was_ accepted on the client, and that compilation was successfu
- After removing the terminal "clear" from webpack, it was then evident that the client was compiling and the server was not - this narrowed it down to a server configuration problem, rather than anything wrong with our components. …

Fix unreliable server-side hot reloading

---

CHANGELOG.md
package.json
src/config/createWebpackConfig.js
src/server/render/default-document/index.js

We couldn't reproduce this issue locally but this will protect us against it happening on Heroku again.
`assets.json` on Heroku included all other chunks (split js, css files, json) as well as the entry files(client, vendor), whereas locally (and previously on Heroku 🤔) it has always _only_ included the entry files.

Incorrect asset chunks

---

src/config/createWebpackConfig.js
test/fixtures/build-with-custom-webpack/webpack.config.js

Added support for an object export from a custom webpack config.
As a result, module exports can be objects:
```
module.exports = {
default: () => {
}
}
```
or functions:
```
module.exports = () => {}
```

Webpack custom configuration check

---

CHANGELOG.md
bin/dev.js
package.json

During development, the client will receive websocket events indicating the beginning and end of a server compile.
This will allow for the client to re-render SSR iFrame and embeds without a race condition, as well as providing a route for developing UI that could indicate server compile status
NB - This does not affect the client scripts at all - to utilise these events you will need to hook into websockets natively or via libary like sock.js
Example from Create React App here:
https://github.com/facebook/create-react-app/blob/4562ab6fd80c3e18858b3a9a3828810944c35e36/packages/react-dev-utils/webpackHotDevClient.js#L60

Feature / Broadcast server compilation events to the client

---

src/client/index.js
src/server/handlers/dynamic.js

- Set cache for all preview links, rely on Tapestry Wordpress Plugin to produce unique hash per content update
- Remove tapestry query string data from URL on load

Fix: Preview cache

---

CHANGELOG.md
package.json
src/server/handlers/dynamic.js
src/server/render/tapestry-render.js

Removed a bunch of unnecessary code from `dynamic` and removed the duplicated `normalisedPath()` from tapestry-render.
Fixes non-matching path when using `/`

Fix: Normalised path

---

CHANGELOG.md
package.json
src/server/render/error-view.js
src/server/render/tapestry-render.js
test/server/error-view.test.js

Allows the user to pass a route of `{ path: '/error-please', error: true }` to return a 404 and Error view without touching the API.
Also tweaked the error component handling to only return (and bundle) a Tapestry default `missing` or `error` if we're not in production mode.

Fix: Error route

---

src/server/handlers/api.js
src/server/render/tapestry-render.js
src/server/utilities/base-url-resolver.js
test/server/preview.test.js

Allows overriding the default baseUrl behaviour for the route, this includes the preview `revisions` endpoint.
```js
{
path: '/something'
endpoint: '/posts?123'
options: {
baseUrl: 'https://www.somewhere.com/wp-json/wp/v2'
}
}
```

Feature: Base url route option

---

bin/start.js
package.json
src/config/hot.js
src/config/production-server.js
src/server/index.js
src/server/utilities/logger.js
yarn.lock

Tapestry will not listen in the heroku port anymore. Nginx will and it will proxy pass to tapestry running on port 3000.
Added a LOG_PATH where the `access.log` and `error.log` will live in the server, this 2 files will be redirected to `stdout` which is where `heroku logs` reads from.

Create TAPESTRY_HOST and TAPESTRY_PORT env vars and move logs to a file

---

package.json
test/server/redirects.test.js

- changed the `PORT` env to `TAPESTRY_PORT` in the tests
- changed the `LOG_LEVEL` in the tests, as `silent` is breaking the tests with the new version of winston logger

fix integration tests

---

CHANGELOG.md
package.json
readme.md
src/server/handlers/dynamic.js
src/server/render/render-success-tree.js
src/server/render/render-tree-to-html.js
src/server/render/tapestry-render.js
test/server/headers.test.js
yarn.lock

Added functionality whereby the client can access headers passed during the browser's request.
Client's tapestry.config.js file may now include, for instance ```headers: ['location', 'connection-speed']``` , and these will be available in the _tapestry object that is generated.

Get headers

---

CHANGELOG.md
package.json
readme.md
src/server/handlers/dynamic.js

Cache key modifier functionality added. Client can now add a function in their tapestry config if they want to run some logic to ensure different cache keys based on the request and initial cache key.
An example of the usefulness of this feature would be the ability to generate a different cache based on the country the user is browsing from.

added cache key modifier

---

CHANGELOG.md
package.json
readme.md
src/server/handlers/dynamic.js
src/server/handlers/purge.js
src/server/index.js
src/server/utilities/cache-manager.js
test/server/cache.test.js

Created a new method on `tapestry.config.js` to allow users to declare all possible keys for a cache entry. This allows Tapestry to clear all instances of the cache entry and not just the default one.
Moved the heavy lifting of the cache keys and running those methods into the cache-manager utility.

Fix: Cache purge
